language: node_js

node_js:
  - 'stable'
  - '8'
  
sudo: false

env:
  - workerCount=2

matrix:
  fast_finish: true

branches:
  only:
  - master

install:
  - npm install

git:
  depth: 1